<?php

namespace app\Classes\Const\DatabaseConst;

class DivisionTableConst
{
    const CONST_TABLE_NAME_OF_DIVISION = 'divisions';

    const CONST_FOREIGN_ID_KEY_OF_DIVISION_ID = 'division_id';
    
    const CONST_CLM_NAME_OF_DIVISION_TABLE_DIVISION = 'division';
    const CONST_CLM_NAME_OF_DIVISION_TABLE_DIVISION_VALUE = 'division_value';


    const CONST_TABLE_NAME_OF_DIVISION_MASTERS = 'division_masters';

    const CONST_FOREIGN_ID_KEY_OF_DIVISION_MASTER_CODE = 'division_master_code';
    
    const CONST_CLM_NAME_OF_DIVISION_MASTERS_TABLE_DIVISION_MASTER = 'division_master';
    const CONST_CLM_NAME_OF_DIVISION_MASTERS_TABLE_DIVISION_MASTER_CODE = 'division_master_code';

    const CONST_VALUE_DIVISION_MASTER_KNOWLEDGE_STATUS = 'knowledge_status';
    
    const CONST_VALUE_DIVISION_MASTER_PROJECT_STATUS = 'project_status';
        const CONST_VALUE_OF_PROJECT_STATUS_NOT_STARTED = 1;
        const CONST_TEXT_OF_PROJECT_STATUS_NOT_STARTED = '未着手';
        const CONST_VALUE_OF_PROJECT_STATUS_STARTED = 2;
        const CONST_TEXT_OF_PROJECT_STATUS_STARTED = '着手';
        const CONST_VALUE_OF_PROJECT_STATUS_IN_CHECK = 3;
        const CONST_TEXT_OF_PROJECT_STATUS_IN_CHECK = '確認中';
        const CONST_VALUE_OF_PROJECT_STATUS_REDO = 4;
        const CONST_TEXT_OF_PROJECT_STATUS_REDO = '差し戻し';
        const CONST_VALUE_OF_PROJECT_STATUS_IN_CORRECT = 5;
        const CONST_TEXT_OF_PROJECT_STATUS_IN_CORRECT = '修正対応中';
        const CONST_VALUE_OF_PROJECT_STATUS_FINISHED = 9;
        const CONST_TEXT_OF_PROJECT_STATUS_FINISHED = '完了';
        const CONST_VALUE_OF_PROJECT_STATUS_DESTRUCTED = 10;
        const CONST_TEXT_OF_PROJECT_STATUS_DESTRUCTED = '破棄';
        


    const CONST_VALUE_DIVISION_MASTER_TASK_STATUS = 'task_status';
        const CONST_VALUE_OF_TASK_STATUS_NOT_STARTED = 1;
        const CONST_TEXT_OF_TASK_STATUS_NOT_STARTED = '未着手';
        const CONST_VALUE_OF_TASK_STATUS_STARTED = 2;
        const CONST_TEXT_OF_TASK_STATUS_STARTED = '着手';
        const CONST_VALUE_OF_TASK_STATUS_IN_CHECK = 3;
        const CONST_TEXT_OF_TASK_STATUS_IN_CHECK = '確認中';
        const CONST_VALUE_OF_TASK_STATUS_REDO = 4;
        const CONST_TEXT_OF_TASK_STATUS_REDO = '差し戻し';
        const CONST_VALUE_OF_TASK_STATUS_IN_CORRECT = 5;
        const CONST_TEXT_OF_TASK_STATUS_IN_CORRECT = '修正対応中';
        const CONST_VALUE_OF_TASK_STATUS_FINISHED = 9;
        const CONST_TEXT_OF_TASK_STATUS_FINISHED = '完了';
        const CONST_VALUE_OF_TASK_STATUS_DESTRUCTED = 10;
        const CONST_TEXT_OF_TASK_STATUS_DESTRUCTED = '破棄';

    const CONST_VALUE_DIVISION_MASTER_IMPORTANCE = 'importance';
        const CONST_VALUE_OF_IMPORTANCE_HIGHEST = 1;
        const CONST_TEXT_OF_IMPORTANCE_HIGHEST = '最高';
        const CONST_VALUE_OF_IMPORTANCE_HIGH = 2;
        const CONST_TEXT_OF_IMPORTANCE_HIGH = '高';
        const CONST_VALUE_OF_IMPORTANCE_MIDDLE = 3;
        const CONST_TEXT_OF_IMPORTANCE_MIDDLE = '中';
        const CONST_VALUE_OF_IMPORTANCE_LOW = 4;
        const CONST_TEXT_OF_IMPORTANCE_LOW = '低';
        const CONST_VALUE_OF_IMPORTANCE_LOWEST = 5;
        const CONST_TEXT_OF_IMPORTANCE_LOWEST = '最低';

    const CONST_VALUE_DIVISION_MASTER_URGENCY = 'urgency';
        const CONST_VALUE_OF_URGENCY_HIGHEST = 1;
        const CONST_TEXT_OF_URGENCY_HIGHEST = '最高';
        const CONST_VALUE_OF_URGENCY_HIGH = 2;
        const CONST_TEXT_OF_URGENCY_HIGH = '高';
        const CONST_VALUE_OF_URGENCY_MIDDLE = 3;
        const CONST_TEXT_OF_URGENCY_MIDDLE = '中';
        const CONST_VALUE_OF_URGENCY_LOW = 4;
        const CONST_TEXT_OF_URGENCY_LOW = '低';
        const CONST_VALUE_OF_URGENCY_LOWEST = 5;
        const CONST_TEXT_OF_URGENCY_LOWEST = '最低';
    }